# Generated by Django 5.2.4 on 2025-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_original', models.TextField()),
                ('title_rewritten', models.TextField()),
                ('description_original', models.TextField(blank=True, null=True)),
                ('description_rewritten', models.TextField(blank=True, null=True)),
                ('content_rewritten', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
