# Generated by Django 5.2.4 on 2026-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Business', 'Business'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
